#! /bin/bash

python3 main.py 170 -p /dev/ttyUSB1 -s 400 \
    && python3 main.py 15 -p /dev/ttyUSB1 -s 300 \
    && python3 main.py 15 -p /dev/ttyUSB1 -s 400 \
    && python3 main.py 15 -p /dev/ttyUSB1 -s 800 \
    && python3 main.py 15 -p /dev/ttyUSB1 -s 1200 \
    && python3 main.py 15 -p /dev/ttyUSB1 -s 300 \
    && python3 main.py 15 -p /dev/ttyUSB1 -s 400 \
    && python3 main.py 15 -p /dev/ttyUSB1 -s 800 \
    && python3 main.py 15 -p /dev/ttyUSB1 -s 1200 \
    && echo "\nAcquisizione finita"
